[package]
name = "ksnotify"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gitlab = "=0.1401.0"
envconfig = "0.10.0"
yaml-rust = "0.4"